if game.PlaceId == 7346416636 then
local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()
local Window = OrionLib:MakeWindow({Name = "Saiji Hub | Pop It Trading✨", HidePremium = false, IntroText = "Saiji hub", SaveConfig = true, ConfigFolder = "TutorialConfig"})

local FarmTab = Window:MakeTab({
	Name = "Duplicate",
	Icon = "rbxassetid://10606719980",
	PremiumOnly = false
})

FarmTab:AddButton({
	Name = "Start Duplicate",
	Callback = function()
      		_G.credits = "Credits to iShield. DISCORD SERVER INVITE LINK: https://discord.gg/x57Xk65xZs"
loadstring(game:HttpGet("https://raw.githubusercontent.com/iShield2005/scripts/master/popittradingdupefree"))()
  end
})

FarmTab:AddButton({
	Name = "Fake Drop",
	Callback = function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/Zykarius1/Popit-trading-scamscript/main/v'))()
wait(0)
local args = {
    [1] = " ",
    [2] = "System"
}

game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack(args))
  	end    
})

local FarmTab = Window:MakeTab({
	Name = "AutoDrops",
	Icon = "rbxassetid://10864966248",
	PremiumOnly = false
})

FarmTab:AddButton({
	Name = "Banana",
	Callback = function()
      		game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("The banana")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("The banana")
  	end    
})

FarmTab:AddButton({
	Name = "XoxBall",
	Callback = function()
      		game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("XOX Ball Rainbow")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("XOX Ball Rainbow")
  	end    
})

FarmTab:AddButton({
	Name = "Baller",
	Callback = function()
      		game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Baller")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Baller")
  	end    
})

FarmTab:AddButton({
	Name = "BabyFlamingo",
	Callback = function()
      		game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Flamingo Baby")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Flamingo Baby")
  	end    
})

FarmTab:AddButton({
	Name = "Piano",
	Callback = function()
      		game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Piano")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Piano")
  	end    
})

local FarmTab = Window:MakeTab({
	Name = "AutoDrops 2",
	Icon = "rbxassetid://11032345072",
	PremiumOnly = false
})

FarmTab:AddButton({
	Name = "Ice Skates",
	Callback = function()
      		game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Ice Skates")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Ice Skates")
  	end    
})

FarmTab:AddButton({
	Name = "Unicornio",
	Callback = function()
      		game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer("Unicornio")
wait(0.4)
game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer("Unicornio")
  	end    
})

local FarmTab = Window:MakeTab({
	Name = "Upcoming!",
	Icon = "rbxassetid://6193350202",
	PremiumOnly = false
})

end
OrionLib:Init()
